gvalkov/python-evdev

evdev/device.py
The device I'm working with supports SND_BELL, and I need an API for it.
We already have `set_led()`, but there are no API for other etypes.
Instead of adding `set_snd()`, etc, I suggest a generic `set()` method.
=> Generalization of `set_led()`

evdev/uinput.c, evdev/uinput.py
This is necessary to support devices with EV_LED and EV_SND (Maybe others?)
This is related to the issue #45 I opened a few days ago.
Please notice that the implementation of `uinput.read()` is the same as `device.read()`.
I was a bit unconfortable with this until I notices that `device.set_led()` uses `_uinput.write`.
I believe that's OK, since both classes are perfectly symetric to each other
=> Support for read() operation on UInput

evdev/device.py, evdev/eventio.py, evdev/uinput.py
The new asyncio API is very powerful, and much easier than working with selectors directly.
This patch adds the coroutines `async_read` and `async_read_one`, and makes `read_loop()` compatible with the new `async for` syntax.
Unfortunately, the code turned out a bit ugly in order to make the syntax backward compatible with Python 2.7.
=> Support for new asyncio coroutines

evdev/device.py, evdev/eventio.py, evdev/uinput.py
`device`s and `uinput`s are both bidirecional streams of `Input Event`s. and support many of the same operations (read, read_one, read_loop, write, fileno, etc). 
Moving these operations to a superclass seems like a good idea, particularly as I work on #48, which adds a lot of extra shared code
=> Create a baseclass for `device` and `uinput`, to hold the shared read/write functions

evdev/input.c
This one is straightforward :)
=> remove `_input.unpack`, which is used nowhere

evdev/uinput.c, evdev/uinput.py
`phys` is useful to distinguish 2 "identical" devices on the same host.
=> Support setting physical path ("phys") on UInput

evdev/eventio_async.py
If I unplug a device, the loop should end with an error, instead of blocking forever.
Asynchronous programming is hard, you know...
=> async version of `read_loop()` must stop on errors.

setup.py
PyPI has a Python 3.6 trove classifier and evdev builds and runs under that version, amends metadata to reflect this.
=> add python 3.6 classifier to setuptools and pypi

evdev/device.py, evdev/input.c
See https://github.com/gvalkov/python-evdev/issues/81#issuecomment-375335531
Needed because some later kernels (at least from 4.15) have started reporting the bluetooth controller
MAC for bluetooth devices as the phys, rather than the actual physical address of the device (which is
obviously the bit you actually care about in most cases). As with phys, there's no guarantee that uniq
is actually set, so I'm treating it the same way as phys, but modern kernels appear to be putting the bluetooth destination HW address in uniq.
=> Provide access to bluetooth uniq address

evdev/uinput.py
`UIInput.from_device()` tries to remove events from the list of capabilities, even if they are not present in the device's capabilities.
This bit me in a situation that ended up being indicative of a bug in my own code, but one of the event types to be removed by default, (`EV_SYN` or `EV_FF`) was not in the device's list of capabilities, giving me a KeyError.
It seems that if the capability is not present, then it doesn't need to be removed from the capabilities dict. So I've made the removal conditional to prevent this raising a `KeyError`.
=> fix keyerror when filtering capabilities not present

evdev/uinput.py
This prevents a
E       SystemError: Objects/longobject.c:415: bad argument to internal function
when passing in too short of a list on newer versions of cpython.
The underlying issue is that in uinput.c:uinput_create the list access
is not checked for IndexError.  If out of range, it returns null and
sets an error.  At some point PyLong_AsLong started to fail when
passed null (rather than I assume treating it as 0).
This ensures filling with 0 behavior at the python level.
=> FIX: ensure lists handed in to _uinput.create are long enough

evdev/ff.py
This was preventing any force feedback effect that needs the left coefficient from working.
=> Fixing typo in ff Condition, left_coeff

evdev/uinput.c
Since these arguments are treated as uint16_t values, using the 'H' specifier is more logical. Moreover, it allows vendor and product to be greater than or equal to 0x8000.
=> Use H to parse uinput_setup arguments

evdev/uinput.c
Creating a UInput device always ignored the resolution parameter since the c implementation was old for current linux kernels.
I've [a project](https://github.com/LinusCDE/rmTabletDriver) which creates a virtual tablet (absolute pen input). I'm currently working on getting the implementation working in libinput which turned out to be missing the resolution (which I had provided but was seemingly ignored by python-evdev).
This patch adds the capability to define the resolution using the newer way for defining absolute capabilities based on [my c implementation](https://github.com/LinusCDE/rmTabletDriver/blob/master/tabletDriver.c) to fix the problem.
If the new variant isn't supported by the kernel (e.g. old linux kernel or bsd), the current solution will still be used instead.
P.S.: I've …
=> Add UInput support for the resolution parameter in AbsInfo

docs/changelog.rst, docs/tutorial.rst
These were flagged by Lintian, Debian's code-quality tool.
Signed-off-by: Stephen Kitt <steve@sk2.org>
=> Fix a couple of typos

evdev/input.c, evdev/uinput.c
time element is deprecated on new input_event structure in kernel's
input.h [1]
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=152194fe9c3f
=> Fix build on 32bit arches with 64bit time_t

evdev/events.py
Add to the `keys` dictionary when an unknown key is pressed. Fixes issue #91
=> Fix crash when handling unknown keys #91

evdev/device.py, evdev/input.c
Changing AbsInfo data in kernel is useful for setting min/max
calibration for other programs and flatness/fuzz settings are
useful for kernel side filtering of input events
=> Expose get/set absinfo ioctl commands

evdev/input.c
This bug caused values at the end of the list to not be reported back.
Example: On my system, SW_PEN_INSERTED (0x0f) is the last switch constant. That is,
SW_MAX=SW_PEN_INSERTED. Other tools (python-libevdev) correctly reported this switch
as 'set' but python-evdev did not. This commit fixes this issue.
=> Fix off-by-one in ioctl_EVIOCG_bits

docs/changelog.rst, evdev/device.py
It's impossible to set any of the AbsInfo parameters to 0 as it evaluate to False like None so the code was using the current value instead. The proposed fix simply check explicitly that the value is not None instead of false.
=> Fix set_absinfo to allow setting parameters to zero

docs/tutorial.rst, evdev/uinput.py
Fixes code bug discussed in #135 
Minimal change, but do let me know if you'd like it done differently! I briefly tested this on my machine and it works as expected.
=> Add missing return codes to os.strerror() calls and fix force feedback example in docs.

evdev/input.c
Discovered a leak related to the read method for an InputDevice, when it returns a BlockingIOError while there is nothing to read. Ultimately tracked it down to a reference counting bug in device_read_many in input.c. Was able to recreate it using the following script
```python
import evdev
import objgraph
import select
import time
def test_device_read_leak(device_name):
device = evdev.InputDevice(device_name)
start_time = time.time()
while time.time() - start_time < 30:
r, _, _ = select.select([device.fd], [], [], 0.1)
try:
for event in device.read():
pass
except BlockingIOError:
pass
print("Before loop calling device.read() ~300 times")
objgraph.show_growth()
test_device_read_leak('/dev/input/event2')
print("\nAfter loop")
objgraph.show_growth()
```
Results before change
```
Before loop …
```
=> Fix leak when returning BlockingIOError from a read 

evdev/ff.py
The Envelope struct defined an 'attach_length' key instead of the
expected 'attack_length'. While the documentation was correct, any
passed in 'attack_length' value was being silently dropped.
This was discovered when configuring a periodic sinusoidal effect
and observing differences in the waveform in comparison to the C API.
Signed-off-by: Paul Mundt <paul.mundt@adaptant.io>
=> ff: Fix up attack_length key typo in Envelope struct

evdev/device.py
see https://github.com/gvalkov/python-evdev/issues/144
I don't know if the rest of the code relies on a blocking os.close, but it solves my issue. It doesn't seem to cause any unwanted side effects in my use case (https://github.com/sezanzeb/key-mapper), everything works fine.
=> threaded non-blocking close

evdev/eventio_async.py
fixes https://github.com/lutris/lutris/issues/3250
_do_when_readable is only used for e.g. async_read, but InputDevice may not use that and use read instead. So _do_when_readable is never called and no event loop is needed.
=> fixing "There is no current event loop in thread" for non asyncio code

docs/tutorial.rst
The imports were for classes, while the example was referencing the package name
=> Fix imports in sample

docs/tutorial.rst
The "Injecting an FF-event into first FF-capable device found" example was slightly broken, with a missing import and a typo on what is now line 450 (previously 449) - should be ecodes.EV_FF and not e.EV_FF. Finally, added a duration_ms of time.sleep(), as otherwise the effect immediately gets erased and doesn't seem to do anything.
=> Update tutorial.rst (fixed FF example)

docs/tutorial.rst
This example:
```py
from evdev import InputDevice
from selectors import DefaultSelector, EVENT_READ
selector = selectors.DefaultSelector()
keybd = evdev.InputDevice('/dev/input/event2')
selector.register(keybd, selectors.EVENT_READ)
```
To this:
```py
from evdev import InputDevice
from selectors import DefaultSelector, EVENT_READ
selector = DefaultSelector()
keybd = InputDevice('/dev/input/event2')
selector.register(keybd, EVENT_READ)
```
=> Importing modules was wrong in `selector`

evdev/device.py
Fix ImportError, AttributeError, maybe a generic Exception is more pratical
```
Exception ignored in: <bound method InputDevice.__del__ of InputDevice('/dev/input/event12')>
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/evdev/device.py", line 160, in __del__
File "/usr/local/lib/python3.6/dist-packages/evdev/device.py", line 305, in close
File "/usr/local/lib/python3.6/dist-packages/evdev/eventio_async.py", line 55, in close
File "/usr/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
File "/usr/lib/python3.6/asyncio/events.py", line 669, in get_event_loop_policy
File "/usr/lib/python3.6/asyncio/events.py", line 662, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down
```
=> fix ImportError: sys.meta_path is None

evdev/util.py
re.Pattern is not a guaranteed class name of the re module:
```
[   32s] _____________________________ test_match_ecodes_a ______________________________
[   32s] 
[   32s]     def test_match_ecodes_a():
[   32s] >       res = util.find_ecodes_by_regex('KEY_ZOOM.*')
[   32s] 
[   32s] tests/test_util.py:5: 
[   32s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   32s] 
[   32s] regex = 'KEY_ZOOM.*'
[   32s] 
[   32s]     def find_ecodes_by_regex(regex):
[   32s]         '''
[   32s]         Find ecodes matching a regex and return a mapping of event type to event codes.
[   32s]     
[   32s]         Example
[   32s]         -------
[   32s]         >>> find_ecodes_by_regex(r'(ABS|KEY)_BR(AKE|EAK)')
[   32s]         {1: [411], 3: [10]}
[   32s] …
```
=> Fix regex search

evdev/eventio_async.py
From the [Python 3.11 Changelog](https://docs.python.org/3.11/whatsnew/3.11.html):
>The @asyncio.coroutine [decorator](https://docs.python.org/3.11/glossary.html#term-decorator) enabling legacy generator-based coroutines to be compatible with async/await code. The function has been deprecated since Python 3.8 and the removal was initially scheduled for Python 3.10. Use [async def](https://docs.python.org/3.11/reference/compound_stmts.html#async-def) instead. (Contributed by Illia Volochii in [bpo-43216](https://bugs.python.org/issue?@action=redirect&bpo=43216).)
This small change should make things work with python 3.11, the tests are passing for me.
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>
=> evdev/eventio_async.py: python3.11 compatibility

docs/tutorial.rst
Variable `effect_type` was declared but never used, in the ff-event injection example.
=> Put unused variable to use

evdev/genecodes.py, setup.py
Flags are hard to pass when python-evdev is installed as part of another python library. Instead evdev should check standard environment variables that also a C compiler would use to locate a header file.
See: https://gcc.gnu.org/onlinedocs/cpp/Environment-Variables.html
=> respect CPATH/C_INCLUDE_PATH

docs/tutorial.rst, evdev/uinput.c, evdev/uinput.py
Hi, I believe there is a bug as far as setting ff_effects_max when creating ff-capable uinput devices.
Opening a controller device with fftest, I am told.. `Number of simultaneous effects: 16`. With python-evdev I create a uinput device that copies the exact capabilities of this device. For this device, fftest reports.. `Number of simultaneous effects: 96`. Off by 80. 
In the kernel [input.h](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/input.h), I can see `FF_EFFECT_MIN` and `FF_RUMBLE` is defined as 0x50 (80), and represents the offset to calculate the actual number of effects. So FF_EFFECT_MIN should be subtracted from FF_MAX_EFFECTS to set the value expected in ff_effects_max.
This pull request makes the described change in python-evdev's …
=> Set ff_effects_max correctly by subtracting FF_EFFECT_MIN.

evdev/device.py, evdev/input.c, evdev/uinput.c, evdev/uinput.py
As discussed in issue #205. Finds the device node on Linux systems that support UI_GET_SYSNAME in the same way that libevdev does.
I haven't implemented the FreeBSD variant of the logic yet because (1) then I'd have to set up a FreeBSD VM to test it, and (2) the documentation of python-evdev does not even mention FreeBSD as a supported platform. That said, the FreeBSD variant of the function `_find_device_linux` should literally be a simple as:
```py
def _find_device_freebsd(self, sysname):
return device.InputDevice(f'/dev/input/{sysname}')
```
There is some discussion about how the code of `_find_device_fallback` should be updated in issue #204 and #205. This pull request does not integrate those proposed changes.
=> New method for finding the device node corresponding to a uinput device

evdev/device.py
Hi there, I think in most cases it's rather uniq instead of phys one is interested in. E.g., for Bluetooth devices, phys shows the own device's Bluetooth adapter MAC, which is the same for all input devices, whereas uniq shows each device's individual MAC.
=> Print uniq additionally to phys, if available

evdev/uinput.py
It has been reported in issue #214 that even on modern Linux distributions that use devtmpfs, it can take longer than 0.1 seconds before the input device becomes available with the right permissions.
To solve this: if sysfs reports that a specific input device should be used, but it cannot be opened immediately, keep trying again for up to two seconds.
This only adjusts the `_find_device_linux` function, because adding such a loop to `_find_device_fallback` runs at risk of causing issue #205 again on outdated operating systems: if the sought device is not readable yet, but another device with the same name already exists, then there is a risk that we open the other device with the same name instead of the intended one.
(Unless `_find_device_fallback` refuses to return a device if another …
=> Wait up to two seconds for input device to become available.

evdev/uinput.c
The Python code is already ready to deal with `uinput_get_sysname()` throwing OSError in case the ioctl `UI_GET_SYSNAME` is not available, but it turns out that the C object code refuses to link if the macro `UI_GET_SYSNAME` was not defined at build time, because the compiler assumes that `UI_GET_SYSNAME` is a symbol that will be defined later at link time. (Issue #178)
Add an `#ifdef` guard around the code that relies on `UI_GET_SYSNAME` so that no reference to any hypothetical symbol `UI_GET_SYSNAME` remains in the object code if the `UI_GET_SYSNAME` macro was undefined at build time. This will cause `uinput_get_sysname()` to raise OSError if the `UI_GET_SYSNAME` was not defined at build time.
=> Add #ifdef guards around UI_GET_SYSNAME

evdev/uinput.py
This is required to make python-evdev work on CentOS 7. On CentOS 7, the ecode `FF_MAX_EFFECTS` is not defined, which means that the function definition of `UInput.__init__` fails to run, which causes the whole module to break on import.
=> Provide fallback value for FF_MAX_EFFECTS

evdev/device.py
=> delay and repeat were swapped

.github/workflows/install.yaml, .github/workflows/lint.yml, .github/workflows/test.yml, evdev/ecodes.py, evdev/eventio.py, evdev/events.py, evdev/uinput.py, tests/test_uinput.py
And
- fixed a few pylint errors
- turned RuntimeError into the desired UInputError if the device is not a character device, caused by a re-raise outside an except block
=> Add pylint -E and pytest to ci

evdev/uinput.py, tests/test_uinput.py
Followup for https://github.com/gvalkov/python-evdev/pull/228
~Because the quick fix for the `raise` is still, in some way, using exceptions for control flow, and I don't like raising some exception just to replace it with a different one shortly afterwards. Also, OSError is wrong there and just happened to work for the time being. I also wanted to avoid solutions that define msg multiple times (inside the if, and inside the except), and avoid creating/formatting msg before any exception happened. So it had to be `except: pass` to raise the exception at the end of the method. This is somewhat hard to get beautiful and good-practice.~
edit: looks pretty with assert.
Added 2 more tests.
=> Small character device verification cleanup

src/evdev/__init__.py
Fixes type errors such as:
```
compatibility_device.py:4: error: Module "evdev" does not explicitly export attribute "InputDevice"  [attr-defined]
compatibility_device.py:4: error: Module "evdev" does not explicitly export attribute "categorize"  [attr-defined]
```
Alternative approach is to define `__all__` and list everything in there.
=> Explicit export

src/evdev/device.py, src/evdev/eventio_async.py, src/evdev/util.py
Some quick obvious fixes, plus hopefully all the things needed to fix my type errors. (https://github.com/Dreamsorcerer/bthidhub/actions/runs/13417776510/job/37482761581?pr=29)
=> Fill in some type annotations

setup.py, src/evdev/genecodes_c.py
`ecodes.c` currently contains the kernel info of the build machine and the full path of the `input*.h` headers: This is not reproducible as output can change even is headers content do not. Downstream distributions might package `ecodes.c` and get non-reproducible output.
To fix this: introduce a `--reproducible` option in the build:
- in `setup.py build_ecodes` command
- in underlying `genecodes_c.py`
Note: These options are disabled by default so no change is expected in current builds.
Here is a sample of the `ecodes.c` output:
```
$ python -m build --config-setting=--build-option='build_ecodes' -n >/dev/null 2>&1; cat src/evdev/ecodes.c |grep Generated
/* Generated on   Linux 6.1.0-31-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.128-1 (2025-02-07) x86_64 */
/* Generated from …
```
=> Add a reproducibility option for building ecodes.c

src/evdev/device.py
This means that dev.path is correctly set to `str` or `bytes`, rather than `str | bytes` or the current `str | bytes | Any`.
Fixes my last typing errors:
https://github.com/Dreamsorcerer/bthidhub/actions/runs/13876066841/job/38828521235?pr=29#step:6:15
=> Use Generic to set precise type for InputDevice.path
